#!/bin/sh

set -eu

if ! cargo +nightly fmt -- --check
then
    echo "There are some code style issues."
    echo "Run cargo fmt first."
    exit 1
fi

if ! cargo clippy --all-targets -- -D warnings
then
    echo "There are some clippy issues."
    exit 1
fi

if ! cargo nextest run --workspace --color=always --release
then
    echo "There are some test issues."
    exit 1
fi

if ! cargo test --doc
then
    echo "There are some doctest issues."
    exit 1
fi

exit 0

